-- Generated by data_generation/schema.py (schema version 2). Do not edit by hand.

-- One generation run: configuration, provenance, status, summary.
CREATE TABLE IF NOT EXISTS runs (
    run_id TEXT NOT NULL,
    name TEXT,
    dataset TEXT,
    application TEXT NOT NULL,
    mode TEXT NOT NULL,
    status TEXT NOT NULL,
    provider TEXT,
    model TEXT,
    config JSONB NOT NULL,
    code_version TEXT,
    code_dirty BOOLEAN,
    schema_version INTEGER NOT NULL,
    summary JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (run_id)
);

COMMENT ON COLUMN runs.name IS 'optional human label for the run';
COMMENT ON COLUMN runs.dataset IS 'groups runs that belong to one dataset (e.g. collected over several sessions)';
COMMENT ON COLUMN runs.application IS 'e.g. tarot_celtic_cross';
COMMENT ON COLUMN runs.mode IS 'live | batch | dry_run';
COMMENT ON COLUMN runs.status IS 'prepared | running | submitted | completed | partial (some requests unfinished) | interrupted';
COMMENT ON COLUMN runs.config IS 'all generation settings (template, params, seed, retries, ...)';
COMMENT ON COLUMN runs.code_version IS 'git commit of the code that produced the run';
COMMENT ON COLUMN runs.code_dirty IS 'uncommitted changes present when the run started';
COMMENT ON COLUMN runs.summary IS 'counts / token totals, filled in when the run finishes';

-- People used as prompt inputs (a snapshot of each persona a run used).
CREATE TABLE IF NOT EXISTS personas (
    persona_id TEXT NOT NULL,
    persona_set TEXT NOT NULL,
    persona_number INTEGER,
    name TEXT,
    payload JSONB NOT NULL,
    content_sha256 TEXT NOT NULL,
    PRIMARY KEY (persona_id)
);

COMMENT ON COLUMN personas.persona_id IS 'the persona''s own id (stable across runs)';
COMMENT ON COLUMN personas.persona_set IS 'set it came from, e.g. tarot_personas';
COMMENT ON COLUMN personas.payload IS 'the full persona record';
COMMENT ON COLUMN personas.content_sha256 IS 'hash of payload; differs if a persona was edited';

-- Structured inputs the prompts are built from (e.g. a card draw).
CREATE TABLE IF NOT EXISTS inputs (
    input_id TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    input_index INTEGER NOT NULL,
    input_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    persona_id TEXT REFERENCES personas(persona_id),
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (input_id)
);

COMMENT ON COLUMN inputs.run_id IS 'run this row belongs to';
COMMENT ON COLUMN inputs.input_index IS 'position within the run';
COMMENT ON COLUMN inputs.input_type IS 'e.g. celtic_cross_draw';
COMMENT ON COLUMN inputs.payload IS 'the input itself, e.g. {position: card state}';
COMMENT ON COLUMN inputs.persona_id IS 'who the prompt is written for; NULL = none';

-- Long form of inputs: one row per labelled element.
CREATE TABLE IF NOT EXISTS input_items (
    input_id TEXT NOT NULL REFERENCES inputs(input_id),
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    item_index INTEGER NOT NULL,
    label TEXT NOT NULL,
    value TEXT NOT NULL,
    entity TEXT,
    qualifier TEXT,
    PRIMARY KEY (input_id, item_index)
);

COMMENT ON COLUMN input_items.run_id IS 'run this row belongs to';
COMMENT ON COLUMN input_items.label IS 'e.g. position ''Outcome''';
COMMENT ON COLUMN input_items.value IS 'full value, e.g. ''Death reversed''';
COMMENT ON COLUMN input_items.entity IS 'value without qualifiers, e.g. ''Death''';
COMMENT ON COLUMN input_items.qualifier IS 'e.g. ''reversed'' / ''upright''';

-- Prompt template versions used by runs: the exact text behind each rendered prompt.
CREATE TABLE IF NOT EXISTS prompt_templates (
    template_sha256 TEXT NOT NULL,
    template_id TEXT NOT NULL,
    name TEXT NOT NULL,
    version INTEGER NOT NULL,
    system_template TEXT,
    user_template TEXT NOT NULL,
    required JSONB NOT NULL,
    optional JSONB NOT NULL,
    description TEXT,
    changes TEXT,
    based_on TEXT,
    status TEXT,
    PRIMARY KEY (template_sha256)
);

COMMENT ON COLUMN prompt_templates.template_sha256 IS 'hash of name, version and template text';
COMMENT ON COLUMN prompt_templates.template_id IS '<name>_v<version>, e.g. celtic_cross_v2';
COMMENT ON COLUMN prompt_templates.required IS 'variables that must be supplied';
COMMENT ON COLUMN prompt_templates.optional IS 'variables that may be omitted, e.g. persona';
COMMENT ON COLUMN prompt_templates.changes IS 'what changed from the previous version, and why';
COMMENT ON COLUMN prompt_templates.based_on IS 'template_id this version was derived from';
COMMENT ON COLUMN prompt_templates.status IS 'locked | draft at the time of the run';

-- Rendered prompts (one input can have several templates).
CREATE TABLE IF NOT EXISTS prompts (
    prompt_id TEXT NOT NULL,
    input_id TEXT NOT NULL REFERENCES inputs(input_id),
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    template TEXT NOT NULL,
    template_sha256 TEXT REFERENCES prompt_templates(template_sha256),
    system TEXT,
    user_text TEXT NOT NULL,
    messages JSONB NOT NULL,
    prompt_sha256 TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (prompt_id)
);

COMMENT ON COLUMN prompts.run_id IS 'run this row belongs to';
COMMENT ON COLUMN prompts.template IS 'template id, e.g. celtic_cross_v1';
COMMENT ON COLUMN prompts.template_sha256 IS 'exact template content used (NULL for schema version 1 runs)';
COMMENT ON COLUMN prompts.messages IS 'exact message list sent';
COMMENT ON COLUMN prompts.prompt_sha256 IS 'hash of messages, for dedup / grouping';

-- One API call specification: prompt + provider + model + params.
CREATE TABLE IF NOT EXISTS requests (
    request_id TEXT NOT NULL,
    prompt_id TEXT NOT NULL REFERENCES prompts(prompt_id),
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    provider TEXT NOT NULL,
    model TEXT,
    params JSONB NOT NULL,
    extra_body JSONB NOT NULL,
    mode TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (request_id)
);

COMMENT ON COLUMN requests.run_id IS 'run this row belongs to';
COMMENT ON COLUMN requests.params IS 'standard params (max_tokens, temperature, ...)';
COMMENT ON COLUMN requests.extra_body IS 'provider-specific params (top_k, min_p, ...)';
COMMENT ON COLUMN requests.mode IS 'live | batch';

-- Provider batch jobs, including validation-retry rounds.
CREATE TABLE IF NOT EXISTS batches (
    batch_id TEXT NOT NULL,
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    provider TEXT NOT NULL,
    round INTEGER NOT NULL,
    endpoint TEXT,
    status TEXT NOT NULL,
    raw_status TEXT,
    n_requests INTEGER NOT NULL,
    request_counts JSONB,
    input_file TEXT,
    collected BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (batch_id)
);

COMMENT ON COLUMN batches.run_id IS 'run this row belongs to';
COMMENT ON COLUMN batches.round IS '0 = initial submission, 1.. = retry rounds';
COMMENT ON COLUMN batches.status IS 'pending | running | completed | failed | expired | cancelled';
COMMENT ON COLUMN batches.collected IS 'results written to responses';

-- Every generation attempt (validation retries and resumed API failures included) and its metadata. A request's final response is its highest attempt (see the final_responses view).
CREATE TABLE IF NOT EXISTS responses (
    response_id TEXT NOT NULL,
    request_id TEXT NOT NULL REFERENCES requests(request_id),
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    attempt INTEGER NOT NULL,
    batch_id TEXT REFERENCES batches(batch_id),
    model TEXT,
    finish_reason TEXT,
    error TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    received_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (response_id)
);

COMMENT ON COLUMN responses.response_id IS '<request_id>-a<attempt>';
COMMENT ON COLUMN responses.run_id IS 'run this row belongs to';
COMMENT ON COLUMN responses.attempt IS '1-based, continues across resumes; the highest attempt is the request''s final response';
COMMENT ON COLUMN responses.batch_id IS 'batch that produced it (NULL for live)';
COMMENT ON COLUMN responses.model IS 'model reported by the provider';
COMMENT ON COLUMN responses.error IS 'API error; NULL on success';
COMMENT ON COLUMN responses.received_at IS 'when the row was written';

-- Generated text, kept apart from the narrow metadata table.
CREATE TABLE IF NOT EXISTS response_texts (
    response_id TEXT NOT NULL REFERENCES responses(response_id),
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    text TEXT,
    n_chars INTEGER,
    PRIMARY KEY (response_id)
);

COMMENT ON COLUMN response_texts.run_id IS 'run this row belongs to';

-- Validation verdict for each attempt.
CREATE TABLE IF NOT EXISTS validations (
    response_id TEXT NOT NULL REFERENCES responses(response_id),
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    validator TEXT,
    passed BOOLEAN,
    n_errors INTEGER,
    n_warnings INTEGER,
    validator_error TEXT,
    details JSONB,
    PRIMARY KEY (response_id)
);

COMMENT ON COLUMN validations.run_id IS 'run this row belongs to';
COMMENT ON COLUMN validations.passed IS 'NULL if the validator crashed';
COMMENT ON COLUMN validations.details IS 'per-check details, e.g. extracted {position: card}';

-- One row per validation issue.
CREATE TABLE IF NOT EXISTS validation_issues (
    response_id TEXT NOT NULL REFERENCES responses(response_id),
    run_id TEXT NOT NULL REFERENCES runs(run_id),
    issue_index INTEGER NOT NULL,
    check_name TEXT NOT NULL,
    code TEXT NOT NULL,
    severity TEXT NOT NULL,
    label TEXT,
    message TEXT,
    data JSONB,
    PRIMARY KEY (response_id, issue_index)
);

COMMENT ON COLUMN validation_issues.run_id IS 'run this row belongs to';

-- The response returned for each request: its highest attempt.
CREATE OR REPLACE VIEW final_responses AS
SELECT DISTINCT ON (request_id) *
FROM responses
ORDER BY request_id, attempt DESC;

